#!/usr/bin/env python3
"""Minimal Muslin executable generated by Fab7."""

from __future__ import annotations

import json
import subprocess
import sys


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    if arguments != ["start", "--json"]:
        print("usage: muslin start --json", file=sys.stderr)
        return 2
    process = subprocess.run(
        ["fab7", "--version"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=30,
        check=False,
    )
    result = {
        "ok": process.returncode == 0,
        "extension": "muslin",
        "fab7_version": process.stdout.strip() if process.returncode == 0 else None,
    }
    print(json.dumps(result, sort_keys=True))
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
